import { Geist, Geist_Mono } from "next/font/google";
import "./_styles/globals.css";
import Header from "./_components/Header";

export const metadata = {
	title: "English Jony",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="min-h-full flex flex-col">
				<Header />
				{children}
			</body>
		</html>
	);
}
