// English questions follow the Multiple Choice tasks in each generated lesson.
// The Vietnamese answer choices remain bilingual listening practice content.
export const englishMcQuestions = {
	"office-introduction": {
		"meeting-tom": [
			"What is Maria's job?",
			"What is special about today for Tom?",
			"What does “so far” mean here?",
			"How is Tom feeling?",
			"What does “pretty” mean in “Pretty good”?",
			"What does Maria say about the people at the company?",
			"What does “helping me out” mean here?",
			"What does “show you around” mean here?",
		],
		"meet-coworkers": [
			"What is Tom's job?",
			"What does Anna say to welcome Tom?",
			"What is Tom asking Anna?",
			"How long has Anna worked at the company?",
			"What does Tom usually work with?",
			"What area does Anna work in?",
			"Which sentence is closest in meaning to “I'm looking forward to it”?",
			"A coworker says, “We'll probably work together a lot.” How could you reply?",
			"What does Anna mean by “Just let me know”?",
			"What does Maria want to do next?",
		],
		"talk-about-work": [
			"What is Tom asking Anna?",
			"What is Anna doing?",
			"Who does Tom want to know the website is for?",
			"What does Anna mean by “Yes, it is”?",
			"What is Tom asking Anna?",
			"Who is working with Anna on the project?",
			"What does Tom want to know?",
			"What two things is Anna doing?",
			"What is Tom doing when he asks “Do you need help”?",
			"How does Tom respond when Anna asks for help?",
		],
		"lunch-break": [
			"What is Maria asking Tom?",
			"What does Tom invite Maria to do?",
			"What does Maria want to know?",
			"How does Tom usually prepare his lunch?",
			"What is Tom eating today?",
			"What did Maria bring to eat?",
			"Does Tom eat at the company every day?",
			"About how long is the lunch break?",
			"What is “Let's grab coffee” used to suggest?",
			"How does Tom feel about Maria's suggestion?",
		],
	},
	"weekend-camping": {
		"arriving-at-the-campsite": [
			"What place does Mia mean by “here”?",
			"Which place does Leo mean by “that”?",
			"What does “over” mean in “I'll bring our bags over”?",
			"Why does Mia ask “Do we need anything else”?",
			"Why does Leo ask this question?",
			"Why does Mia check the ground?",
		],
		"setting-up-the-tent": [
			"What is Leo asking Mia to do?",
			"What does “it” refer to in Mia's sentence?",
			"What is Mia checking when she asks “Like this”?",
			"What place does “there” refer to?",
			"What is Mia asking Leo?",
			"What place does “the other side” refer to?",
			"What does Leo mean when he says they are “almost done”?",
		],
		"cooking-dinner": [
			"What does Leo suggest doing?",
			"What ingredients does Leo say they have?",
			"What does Mia want Leo to give her?",
			"How do they know it is time to put the noodles in the pot?",
			"How long does Leo say they should cook the noodles?",
		],
		"talking-by-the-campfire": [
			"How does Leo feel after dinner?",
			"What activity did Mia like best?",
			"What did Leo enjoy doing today?",
			"What does Mia ask Leo about tomorrow?",
			"Where does Leo suggest going tomorrow?",
			"What do Leo and Mia do at the end of their conversation?",
		],
	},
	"asking-for-directions": {
		"finding-a-cafe": [
			"Why does Ben call Emma?",
			"Where is Ben when he says this?",
			"What should Ben do after walking straight ahead?",
			"What does Ben want to confirm?",
			"What does “next to” mean?",
			"What landmark does Emma give Ben to help him find the cafe?",
			"Where is the cafe in relation to Ben's current location?",
			"Where will Emma meet Ben?",
		],
		"finding-the-bus-stop": [
			"What place is Ben looking for?",
			"What does Emma tell Ben to do first?",
			"What does Ben want to confirm?",
			"Where does Emma say the bank is?",
			"What does “across from” mean?",
			"What else does Ben want to know about the bus stop?",
			"About how long will it take Ben to walk to the bus stop?",
		],
		"finding-the-train-station": [
			"Which train does Emma suggest Ben take?",
			"How does Emma tell Ben to buy a ticket?",
			"Where should Ben go, and when will the train leave?",
			"What does Ben want to know?",
			"How long does the trip to Lake Town take?",
			"Does Ben need to change trains to get to Lake Town?",
			"When would you say “Have a good trip!”?",
		],
		"going-to-the-supermarket": [
			"What does Emma's answer tell Ben?",
			"What does Ben mean by “learning my way around”?",
			"What does Ben want Emma to help him find out?",
			"What should Ben do when Emma says “go past the bank”?",
			"Where should Ben turn right after passing the bank?",
			"Where is the supermarket in relation to the bakery?",
			"How does Emma suggest getting to the supermarket, and how long will it take?",
		],
	},
	"at-a-hotel": {
		"asking-for-extra-towels": [
			"What does Ben need from the hotel?",
			"Why does Maya ask for Ben's room number?",
			"What will the hotel staff do next?",
			"What else does Ben want to know?",
			"Where does Ben want the staff to leave the towels?",
		],
		"checking-in": [
			"Why does Ben say “I'd like to…”?",
			"What does this information help Maya do?",
			"What does Maya need to know to continue the check-in?",
			"What information is Maya giving Ben?",
			"Why does Maya say the final line?",
		],
		"checking-out": [
			"What does Ben want to do?",
			"What information does Maya need from Ben?",
			"What will Maya do next?",
			"How much does Ben need to pay?",
			"What is Ben asking about?",
		],
		"reporting-a-room-problem": [
			"What problem is Ben having?",
			"Why does Maya ask for Ben's room number?",
			"What is Maya trying to check?",
			"What will Maya do next?",
			"What else does Ben want to know?",
		],
	},
	"coffee-shop": {
		"asking-about-the-wifi": [
			"Why does Ben ask this question?",
			"How does the word “Great” show Ben feels?",
			"Why does Ben ask for more information?",
			"What kind of help does Ben need?",
			"What does Ben need to do first?",
		],
		"choosing-a-snack": [
			"Why does Emma ask this question?",
			"What does the second sentence explain?",
			"What is Emma doing?",
			"Why does Ben ask this before choosing a snack?",
			"What does Ben's comment tell you?",
			"What is Ben expressing?",
		],
		"fixing-an-order": [
			"Why does Ben begin with “Excuse me”?",
			"What is Ben helping Alex do by saying this?",
			"What does this information help Alex understand?",
			"What kind of sentence is this?",
			"What does Alex's answer show?",
		],
		"ordering-a-coffee": [
			"Why does Emma ask this question?",
			"What does Ben's comment tell you?",
			"What is Emma doing?",
			"What is Emma suggesting?",
			"What has Ben done after saying this?",
		],
	},
	"grocery-store": {
		"checking-out": [
			"Which step of shopping are Ben and Emma at when Lee asks this?",
			"What does Ben need to know before paying?",
			"Which payment method does Ben want to use first?",
			"What is Emma thinking about before leaving the checkout?",
			"What does Lee need Ben to confirm?",
		],
		"choosing-food": [
			"What does Ben want to know with this question?",
			"Why does Emma want the small bottle?",
			"What is Emma comparing?",
			"What does Emma want Ben to decide?",
			"What will Ben and Emma do after choosing their food?",
		],
		"finding-items": [
			"What are Ben and Emma deciding?",
			"Why does Ben ask Emma this question?",
			"What does Emma want to find after the milk and eggs?",
			"Why does Ben say “Excuse me” before asking?",
			"Where does Lee say Ben and Emma should look for bread?",
		],
		"making-a-shopping-list": [
			"What are Ben and Emma doing?",
			"What is Emma checking?",
			"What does Ben decide to buy?",
			"What is Emma asking about?",
			"What does Emma mean?",
		],
	},
	"restaurant": {
		"during-the-meal": [
			"How does Emma feel about the soup?",
			"What does Ben say about the chicken pasta?",
			"Why does Alex ask “How is everything?”",
			"What does “Can I have” help Emma do here?",
			"Does Emma need anything else?",
		],
		"getting-a-table": [
			"How many people need a table?",
			"What is “Do you have” used to ask in this line?",
			"What does Ben want to know about the table near the window?",
			"What does “That sounds good” show Emma thinks?",
			"Which table do Ben and Emma choose?",
		],
		"ordering-food": [
			"What is Alex doing?",
			"How does “Would you like” help Alex ask a question?",
			"What does Emma do after Ben orders?",
			"What is “Can I have” used for here?",
			"Why does Alex repeat the food and drinks?",
		],
		"reading-the-menu": [
			"What does “do you want” help Emma ask here?",
			"Which dish catches Ben's attention?",
			"Why does Ben say “What about”?",
			"What does Emma want to know about the soup?",
			"What have Ben and Emma done so far?",
		],
	},
};

// Grammar and usage answers explain English patterns, so they need English text.
// The original option strings remain the answer values for validation.
export const englishMcOptions = {
	restaurant: {
		"during-the-meal": {
			14: ["Ask whether the guests are ready to pay.", "Ask how the guests like their meal.", "Ask whether the guests want another table.", "Ask whether the guests have a reservation."],
			19: ["Say she already has water.", "Ask where the water is.", "Politely ask for more water.", "Say she does not want water."],
		},
		"getting-a-table": {
			8: ["Ask whether the guests have a reservation.", "Ask what the guests want to eat.", "Ask how the guests want to pay.", "Say goodbye as the guests leave."],
			17: ["Emma does not understand Alex.", "Emma does not want that table.", "Emma thinks that choice is suitable.", "Emma wants to leave the restaurant."],
		},
		"ordering-food": {
			10: ["Politely ask what else the guest wants.", "Ask the guest to pay.", "Ask where the guest is from.", "Say that a dish is sold out."],
			16: ["Say that Emma already has bread.", "Ask where the bread is.", "Politely ask for more bread.", "Say that Emma does not like bread."],
		},
		"reading-the-menu": {
			6: ["What Ben has eaten.", "Whether Ben likes the restaurant.", "What Ben wants to drink.", "What Ben wants to try."],
			14: ["Refuse the soup.", "Suggest the tomato soup.", "Ask the price of the soup.", "Call the server."],
		},
	},
};
