// Generated by the content builder; contains only published offline glossaries.
import glossary0 from "./glossaries/restaurant/getting-a-table.json" with { type: "json" };
import glossary1 from "./glossaries/stories/ten-minutes-a-day/the-old-book.json" with { type: "json" };

export const lessonGlossaries = [glossary0, glossary1];
